site_name:        ExtractMacro.jl
repo_url:         https://github.com/carlobaldassi/ExtractMacro.jl
site_description: Julia package ExtractMacro.jl
site_author:      Carlo Baldassi

theme: yeti

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
